### ISSUE TITLE
[Test] 테스트 코드 작성 및 수정

### ISSUE THREAD

**Issue by juwon-code** [juwon-code/dcs-coffee-shop#1]
### Description
프로젝트의 Controller, Repository 테스트 코드를 수정하고, Service 단위 테스트를 추가한다.

### Tasks
- [ ] Controller 테스트 코드 수정
- [ ] Repository 테스트 코드 수정
- [ ] Service 테스트 코드 작성

### Reference
